#!/usr/bin/env python3
"""Generate config/samples.tsv and config/config.yaml for the sm-vcf-annotation pipeline.

Scans a VCF directory, discovers samples, and generates pipeline config files.

Two modes:
  Interactive:  python scripts/generate_config.py          (guided wizard)
  Flags:        python scripts/generate_config.py --vcf-folder /path/to/vcfs

Usage:
    python scripts/generate_config.py
    python scripts/generate_config.py --vcf-folder /data/vcfs
    python scripts/generate_config.py --vcf-folder /data/vcfs --dry-run
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    sys.exit(
        "Error: pandas is required but not installed.\n"
        "Install it with: pip install pandas\n"
        "(pandas is already available in Snakemake conda environments.)"
    )


# ---------------------------------------------------------------------------
# Section A: VCF Discovery
# ---------------------------------------------------------------------------


def discover_vcf_files(vcf_folder: str | Path) -> list[dict]:
    """Scan a directory for VCF files and return metadata.

    Returns a list of dicts with keys: path, basename, size_bytes.
    """
    folder = Path(vcf_folder)
    if not folder.is_dir():
        return []

    entries = []
    for vcf in sorted(folder.glob("*.vcf.gz")):
        if vcf.is_file():
            entries.append(
                {
                    "path": str(vcf),
                    "basename": vcf.name.replace(".vcf.gz", ""),
                    "size_bytes": vcf.stat().st_size,
                }
            )
    return entries


def format_size(size_bytes: int) -> str:
    """Convert bytes to human-readable format."""
    value = float(size_bytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} PB"


# ---------------------------------------------------------------------------
# Section B: Sample & Config Generation
# ---------------------------------------------------------------------------


def build_samples_dataframe(vcf_entries: list[dict]) -> pd.DataFrame:
    """Create a samples DataFrame from discovered VCF entries."""
    rows = []
    for entry in vcf_entries:
        rows.append(
            {
                "sample": entry["basename"],
                "vcf_basename": entry["basename"],
            }
        )
    return pd.DataFrame(rows)


def write_samples_tsv(
    df: pd.DataFrame,
    output_path: str | Path = "config/samples.tsv",
    *,
    dry_run: bool = False,
    overwrite: bool = False,
) -> str:
    """Write samples DataFrame to TSV.

    Returns the content that was (or would be) written.
    """
    content: str = df.to_csv(sep="\t", index=False)
    path = Path(output_path)

    if dry_run:
        return content

    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists. Use --overwrite or delete it first.")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return content


def generate_config_template(
    vcf_folder: str = "results/final",
    output_path: str | Path = "config/config.yaml",
    *,
    dry_run: bool = False,
    overwrite: bool = False,
) -> str:
    """Generate a config.yaml template with discovered paths.

    Returns the YAML content that was (or would be) written.
    """
    content = f"""\
# =============================================================================
# sm-vcf-annotation configuration
# =============================================================================
# Generated by: python scripts/generate_config.py

ref:
  genome: "/path/to/reference/genome.fa"
  dict: "/path/to/reference/genome.dict"

paths:
  samples: "config/samples.tsv"
  vcf_folder: "{vcf_folder}"
  output_folder: "results/annotation"
  log_subdir: "logs"
  annotation_subdir: "annotation"

snpeff:
  database: "GRCh37.p13"
  extra_flags: "-lof -noInteraction -noMotif -noNextProt -spliceRegionIntronMax 12"

snpsift:
  dbnsfp_db: "dbnsfp/dbNSFP4.9a_grch37.gz"
  dbnsfp_fields: "aaref,aaalt,aapos,SIFT_pred,SIFT4G_score,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,LRT_pred,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationAssessor_score,MutationAssessor_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MVP_score,MVP_rankscore,MPC_score,MPC_rankscore,CADD_raw_rankscore,CADD_phred,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phastCons100way_vertebrate,1000Gp3_AC,1000Gp3_AF,1000Gp3_AFR_AC,1000Gp3_AFR_AF,1000Gp3_EUR_AC,1000Gp3_EUR_AF,1000Gp3_AMR_AC,1000Gp3_AMR_AF,1000Gp3_EAS_AC,1000Gp3_EAS_AF,1000Gp3_SAS_AC,1000Gp3_SAS_AF,gnomAD_exomes_flag,gnomAD_exomes_AC,gnomAD_exomes_AN,gnomAD_exomes_AF,gnomAD_exomes_nhomalt,gnomAD_genomes_flag,gnomAD_genomes_AC,gnomAD_genomes_AN,gnomAD_genomes_AF,gnomAD_genomes_nhomalt,ALFA_Asian_AF,ALFA_Total_AC,ALFA_Total_AN,ALFA_Total_AF,clinvar_id,clinvar_clnsig"

scatter:
  mode: "none"
  count: 100
  canonical_contigs: []

extra_annotations: []
"""

    path = Path(output_path)

    if dry_run:
        return content

    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists. Use --overwrite or delete it first.")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return content


# ---------------------------------------------------------------------------
# Section C: Interactive Mode
# ---------------------------------------------------------------------------


def _interactive_wizard() -> None:
    """Run the interactive config generation wizard."""
    print("=" * 60)
    print("  sm-vcf-annotation — Config Generator")
    print("=" * 60)
    print()

    # Ask for VCF folder
    vcf_folder = input("Path to VCF folder [results/final]: ").strip()
    if not vcf_folder:
        vcf_folder = "results/final"

    # Discover VCFs
    entries = discover_vcf_files(vcf_folder)
    if not entries:
        print(f"\nNo VCF files found in: {vcf_folder}")
        print("Please check the path and try again.")
        return

    print(f"\nFound {len(entries)} VCF file(s):")
    for e in entries:
        print(f"  {e['basename']}.vcf.gz  ({format_size(e['size_bytes'])})")

    # Build samples
    df = build_samples_dataframe(entries)
    print(f"\nGenerated {len(df)} sample(s).")

    # Confirm
    confirm = input("\nWrite config files? [Y/n]: ").strip().lower()
    if confirm in ("n", "no"):
        print("Aborted.")
        return

    # Write files
    try:
        write_samples_tsv(df, overwrite=True)
        print("  Wrote: config/samples.tsv")
    except Exception as e:
        print(f"  Error writing samples.tsv: {e}")

    try:
        generate_config_template(vcf_folder=vcf_folder, overwrite=True)
        print("  Wrote: config/config.yaml")
    except Exception as e:
        print(f"  Error writing config.yaml: {e}")

    print("\nDone! Edit config/config.yaml to set database paths before running.")


# ---------------------------------------------------------------------------
# Section D: CLI Entry Point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate config files for sm-vcf-annotation.",
    )
    parser.add_argument(
        "--vcf-folder",
        type=str,
        default=None,
        help="Path to directory containing input VCF files.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output without writing files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing config files.",
    )

    args = parser.parse_args()

    # Interactive mode if no flags
    if args.vcf_folder is None:
        _interactive_wizard()
        return

    # CLI mode
    entries = discover_vcf_files(args.vcf_folder)
    if not entries:
        print(f"No VCF files found in: {args.vcf_folder}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(entries)} VCF file(s) in {args.vcf_folder}")
    for e in entries:
        print(f"  {e['basename']}.vcf.gz  ({format_size(e['size_bytes'])})")

    df = build_samples_dataframe(entries)

    if args.dry_run:
        print("\n--- samples.tsv ---")
        print(write_samples_tsv(df, dry_run=True))
        print("--- config.yaml ---")
        print(generate_config_template(vcf_folder=args.vcf_folder, dry_run=True))
        return

    write_samples_tsv(df, overwrite=args.overwrite)
    print("Wrote: config/samples.tsv")

    generate_config_template(vcf_folder=args.vcf_folder, overwrite=args.overwrite)
    print("Wrote: config/config.yaml")

    print("\nDone! Edit config/config.yaml to set database paths before running.")


if __name__ == "__main__":
    main()
